version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    command: yarn run start:dev --debug 0.0.0.0:9229
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 9229:9229
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src


